title: UBC Common Look and Feel (CLF)
#unit: Computer Science

description: Site description goes here.

baseurl: "/jekyll-clf-theme"
url: ""
lang: "en"

social:
    name: Jane Doe
    links:
        - https://twitter.com/janedoe
        - https://github.com/janedoe

nav:
  - name: Home
    link: "/"
  - name: About
    link: "/about"
    subnav:
      - name: Contact
        link: "/about/contact"
      - name: Jekyll on Heroku
        link: "/jekyll-on-heroku"
  - name: Help
    link: "/help"
  - name: Nested
    link: "/nested"
    subnav:
      - name: Deep
        link: "/nested/deep"
        subnav:
          - name: Down
            link: "/nested/deep/down"
  - name: Style Guide
    link: styleguide

## don't edit below here unless you want to customize beyond
## changing the menus

markdown: kramdown

theme: jekyll-clf-theme

kramdown:
  input: GFM
  default_lang: clojure
  syntax_highlighter: rouge

highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-scholar

scholar:
  style: apa
  repository: papers
  bibliography_template: bibliography
  bibliography_item_attributes:
    class: paper

# this is where you put your Google analytics tracking ID should you
# wish to use Google analytics (a good idea -- it's free)
tracking_id: #
