title: Jane Doe
unit: Computer Science
name: Jane Doe
description: Site description goes here.

baseurl: "/jekyll-clf-theme"
url: ""
lang: "en"

github_username: janedoe

social:
    name: Jane Doe
    links:
        - https://twitter.com/janedoe
        - https://github.com/janedoe

nav:
  - name: Home
    link: "/"
  - name: About
    link: "/about"
    subnav:
      - name: Contact
        link: "/about/contact"
        subnav:
          - name: Jekyll on Heroku
            link: jekyll-on-heroku.html
  - name: Help
    link: help.html
  - name: Nested
    link: "/nested"
    subnav:
      - name: Deep
        link: "/nested/contact"
        subnav:
          - name: Down
            link: /nested/contact/down

## don't edit below here unless you want to customize beyond
## changing the menus

markdown: kramdown

theme: jekyll-clf-theme

kramdown:
  input: GFM
  default_lang: clojure
  syntax_highlighter: rouge

highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-scholar

scholar:
  style: apa
  repository: papers
  bibliography_template: bibliography
  bibliography_item_attributes:
    class: paper

# this is where you put your Google analytics tracking ID should you
# wish to use Google analytics (a good idea -- it's free)
tracking_id: #
